# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - netflixrecommendation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://netflixrecommendation.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ed9324b06a23444988d350121318e7ad }}
        password: ${{ secrets.AzureAppService_ContainerPassword_228b414508a74b45af034d804df1d7a3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: netflixrecommendation.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ed9324b06a23444988d350121318e7ad }}/netflixrecommendation:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'netflixrecommendation'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_94be32b2490349b4a6785a04f833219f }}
        images: 'netflixrecommendation.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ed9324b06a23444988d350121318e7ad }}/netflixrecommendation:${{ github.sha }}'